" Save to C:/Users/Username

set ignorecase

let mapleader = " "

nnoremap , @q

nnoremap <leader>p "+p
nnoremap <leader>y "+y
vnoremap <leader>y "+y

" mapping to make a view property for xamarin view model
nnoremap <leader>m _iprivate <esc>wy$A;<esc>o<esc>opublic <esc>pByE~o{<CR>get => <esc>pa;<CR>set => SetProperty(ref <esc>pa, value<esc>A;<esc>o}<esc>
nnoremap <leader>n k_Wc2f {<CR><esc>lyiwf,s=<esc>f)C;<CR><esc>"0pA ));<esc>_~IOnPropertyChanged(nameof(<esc>A<cr>}<esc>

" mappings for making mocks
nnoremap <leader>k _iprivate readonly Mock<<esc>llyeA> mock<esc>pA;<esc>
nnoremap <leader>h _dwdwdWea = new <esc>ps(MockBehaviour.Strict)<esc>
nnoremap <leader>j _ElC.Object,<esc>j_

" mappings for replace
nnoremap <leader>r diw"0P
vnoremap <leader>r d"0P

" macro to shorten csproj version syntax
nnoremap <leader>gv j_ditk$i Version="<esc>pEDA" /><esc>jdd._
